application: aegis-demo
version: tests
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static
  login: required

- url: /cron/.*
  script: aegis.app
  login: admin

- url: /.*
  script: aegis.app
  login: required


libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest


builtins:
- remote_api: on


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^submodules/.*
- ^tests/.*
- ^docs/.*

